### ISSUE TITLE
AFR LTS Release

### ISSUE THREAD

**Issue by Supriya-53679** [aws/amazon-freertos-ble-ios-sdk#32] opened 2022-08-30 08:41 UTC
1. When trying ble connection no list is showing but we need to unpair it and then try again(log provided)
2. When trying ble connection, ble list is showing but not getting connected. So we need to unpair and connect again(log will be provided soon)

**Comment by Supriya-53679** [comment] 2022-08-31 08:43
Log is shared below for the first issue in above comment
[Document.docx](https://github.com/aws/amazon-freertos-ble-ios-sdk/files/9460017/Document.docx)

**Comment by Supriya-53679** [comment] 2022-08-31 10:16
Log is shared below for the first issue in above comment
[Document.docx](https://github.com/aws/amazon-freertos-ble-ios-sdk/files/9460623/Document.docx)

**Comment by jasonpcarroll** [comment] 2022-09-01 20:23
Hi @Supriya-53679,
I will take a look.
If you could you provide me with some additional information it would be helpful:
* Library version/commit used.
* iOS version/Phone used
* Hardware you are trying to connect with.
Best,
Jason Carroll

**Comment by ravibhagavandas** [comment] 2022-09-01 23:22
Hi @Supriya-53679 

Could you elaborate the issue further ? 

> When trying ble connection no list is showing

What list are you talking about ? Is it the BLE scan list from the mobile phone before connection or the WiFi network scan list from the IoT device ? 

In the logs above could you point out specific area of logs where the issue is ?

Additional please provide the information as jasonpcaroll mentioned

**Comment by Supriya-53679** [comment] 2022-09-02 05:39
Hi @ravibhagavandas

The ble list that I mentioned was the BLE scan list from the mobile phone. Also in the logs I have highlighted the issue as yellow.

**Comment by Supriya-53679** [comment] 2022-09-02 05:52
Hi @jasonpcarroll 

- Liibrary version for IOS(v1.4.0) and for android (v1.3.0)
- IPhone XR and IOS version is 14.6
- Esp 32 device

**Comment by Supriya-53679** [comment] 2022-09-14 07:28
Hi @ravibhagavandas Gentle Reminder! Please expedite this issue, and also please let me know if there is anything else required from my side.

**Comment by dachalco** [comment] 2022-09-19 23:15
Hey @Supriya-53679

Am trying to reproduce the issue, getting my hands on an iOS device. In the meantime, could you clarify for p.1:
The app starts a BLE scan, and does not list _any_ devices? Or does it rather omit certain devices? If so, which?

**Comment by Supriya-53679** [comment] 2022-09-20 07:39
Hi @dachalco 

If the BLE device is brand new( Not associated with mobile till now), there is no issue in BLE list and making the connection.

But if the device is already paired with mobile app and we want to reprovision the device by making the connection again, that time the issue happens. Sometimes, the device list is not coming and sometimes, even if the list comes, not able to connect with that device until i manually unpair from the mobile setting page.

I don't see it omitting any device in the list

**Comment by dachalco** [comment] 2022-09-21 00:06
@Supriya-53679

Correct me if I'm wrong, then there's 2 issues:
1. Already paired device not showing up in device list -- some times
2. Cannot connect to already paired device that's listed from scan. 

And network provisioning is desired via the (`AmazonFreeRTOSGattService.NetworkConfig UUID:a9d7166a-d72e-40a9-a002-48044cc30100`)?

**Debugging Questions/Info**
Also, to clarify, to my knowledge neither AFR nor the iOS app have LTS releases. 
The title is in reference to the FreeRTOS version _used_ by AFR correct? 
Which version of amazon-freertos are you running on the MCU device?
Are you running the unmodified demo, or is this in regard to a custom amazon-freertos application?
Can you provide MCU device logs and enable the BLE debug logs by setting `IOT_LOG_LEVEL_GLOBAL` as `LOG_DEBUG`. You can define this macro in your `iot_ble_config.h` if it's not already defined.


In the app, the reload icon at the top-left triggers a scan that will only list devices advertising the `AmazonFreeRTOSGattService.DeviceInfo UUID:8a7f1168-48af-4efb-83b5-e679f932ff00`. I'd like to understand how frequently the MCU is advertising the service, and verify whether it's sufficient to be reliably seen by the scan.

**Comment by Supriya-53679** [comment] 2022-09-29 12:58
Hi @dachalco 

Didn't see such messages and as for the testing, we have tested it on iOS 14 & 15 till now.

**Comment by Supriya-53679** [comment] 2022-10-27 09:10
Hi @dachalco 
I have attached the device logs below as mentioned and as of now we are seeing only single device id during re-connect. Also for the device logs, it was tested on:-
Android : Samsung GalaxyA71 , android version : 12,
iPhone XR , iOS 16.1

[awsBLEConnection.docx](https://github.com/aws/amazon-freertos-ble-ios-sdk/files/9877878/awsBLEConnection.docx)

**Comment by dachalco** [comment] 2022-11-11 18:02
Hi @Supriya-53679

In the log I noticed that at startup, the MCU is reporting
> failed to configure restored IRK

IRK is the Identity Resolving Key. A BLE device can randomize its ID address with RPA, but all of its RPA addresses can be resolved to a single ID with the IRK that's shared when devices initially bond. It's my understanding that this version of iOS runs RPA by default, which changes the BLE ID address periodically and possibly when restarting Bluetooth. 

Presumably the first BLE connection attempt in the provided MCU log is meant to stay connected, but without IRK to resolve to a recognized address, it would appear to the MCU as a new unfamiliar device that requires pairing. Could you add the similar `peer_id_addr` logs that print similar values as outlined above? The peer address type should confirm whether iPhone is using RPA address. 


I've not been able to reliably reproduce the issue. I'm reviewing some ESP-IDF issues that were present around the time of this AFR release that may be relevant. But if you are not manually erasing the flash, the MCU should be able to restore the IRK without issue. Currently reviewing some ways you can further detail why IRK restore is failing via logs.

**Closed** 2023-05-26 17:07 UTC
