### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by igorkirnbb** [aws/amazon-freertos-ble-ios-sdk#34] opened 2023-01-11 21:16 UTC
Hello, we have a react-native project with AmazonFreeRTOS and Xcode 14.2. We are experience some issues with building releases:

```
Undefined symbols for architecture arm64:
"OBJC_CLASS$_AWSServiceConfiguration", referenced from:
objc-class-ref in AmazonFreeRTOSDevice.o
"OBJC_CLASS$_AWSEndpoint", referenced from:
objc-class-ref in AmazonFreeRTOSDevice.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Local Debug builds work with 50% chance. Sometimes we have to re-install Pods in order to fix the issues. But the main problem that we are using github actions for prod and because of that builds are always failing. And so far `amazon-freertos-ble-ios-sdk` is the only package which outputs errors in our project with Xcode 14.2 but we really need it for our app. Would it be possible to fix those 2 errors? I know that you already had one Issue created on this topic but its already Closed + we tried everything from that source and nothing helped us. I also believe that the issue might be in the syntax (Swift/Objective-C) and not Cocoapods, because the same config works perfectly fine on Xcode 13. We are ready to provide more info about env if needed and also help with testing fixes and etc.

- **OS:** macOS 13.1
- **Xcode:**  14.2
- **Target iOS:**  14.5

**Comment by poborin** [comment] 2023-01-13 09:45
yeah, I'm facing a very similar issue. I would just add that in my case it fails every time and I have an M1 laptop.

**Comment by igorkirnbb** [comment] 2023-01-13 09:59
Yes, we also using M1 laptops. It also seems like similar issue exist on AWSCore repo. But their workaround needs use_frameworks...which is not ideal for us:(

**Comment by alfred2g** [comment] 2023-01-18 08:08
Hello thanks for reporting, please note that amazon-freertos is deprecated.
Please follow the guidelines for migrating: https://github.com/aws/amazon-freertos/blob/main/DEPRECATED.txt

**Comment by igorkirnbb** [comment] 2023-01-18 19:20
@alfred2g Hi, sorry for my mistake. By amazon-freertos I meant this repo (`amazon-freertos-ble-ios-sdk`) with pod name `AmazonFreeRTOS`.

**Comment by kstribrnAmzn** [comment] 2023-02-06 19:55
@igorkirnbb and @poborin - I'm hoping to get this patched. The only problem here is I'm new to IOS development (our IOS expert switched to another team in Amazon) so I have a couple of questions.

1. Frameworks look to already be enabled for the pod on [this line](https://github.com/aws/amazon-freertos-ble-ios-sdk/blob/master/Podfile#L2) of the podfile. Is there a reason why you're mentioning it needs to be enabled?
2. Rather than using `s.static_framework = true` why not use `use_frameworks! :linkage => :static` instead? Is there some different behavior?

In the meantime - I'm getting setup so that I can reproduce this. I was finally able to update my Mac (now on OSX 13.2) and XCode (14.2).

**Comment by igorkirnbb** [comment] 2023-02-06 20:09
Hey @kstribrnAmzn,  before xcode 14 we could've use plugin `cocoapods-user-defined-build-types` and everything worked fine without any errors, so we didn't need `use_frameworks` in the app Podfile.

Example: 
```
pod 'AmazonFreeRTOS', :build_type => :dynamic_framework
pod 'AWSAuthUI','~> 2.29.1', :build_type => :dynamic_framework
pod 'AWSMobileClient','~> 2.29.1', :build_type => :dynamic_framework
pod 'AWSUserPoolsSignIn', '~> 2.29.1'
```

Regarding second point - yes, we started using `use_frameworks! :linkage => :static` for CI builds because it's the only way to build the app without errors. But with `use_frameworks` we can't use Flipper, so we can't enable it for debug version.
The current workaround we have - Remove Pods folder, after getting 2 errors about symbols, and then re-install all Pods (without any cache cleaning) and launch debug build again. This workaround works fine but it takes so much time, especially with multi environments because we need to re-install Pods every time we switch the scheme.

**Comment by kstribrnAmzn** [comment] 2023-02-17 00:11
Apologies for the delayed response. I was able to snag a coworkers laptop (who has an M1 chip) and found the SDK built. I'll have them rebuild a few times to see if the error occurs.

In the meantime - I'll start reaching out to the AWSCore team. Those errors you've included reference structures/classes/whatever-they're-called-in-swift which would be defined by the AWSCore package. I'm not sure if the issue is how we're consuming this dependency or the dependency itself.

Thank you for your patience on this and if you have suggestions (maybe I'm going about this all wrong) please let me know.

**Comment by kstribrnAmzn** [comment] 2023-02-23 21:25
I have a meeting confirmed with the AWS iOS SDK team this upcoming week. I'll further update this issue with any next steps once I've discussed with them.

**Comment by kstribrnAmzn** [comment] 2023-03-01 16:59
Thanks for your patience here @igorkirnbb and @poborin.

I met with the AWSCore SDK team and brought up the undefined symbols error you are seeing. Their lead engineer also works on an M1 Mac (along with several folks on his team) and mentioned that this issue has only come up with a bad installation of cocoapods. He mentioned installing through ruby/gem causes issues and was able to correct this by first uninstalling through gem and installing through homebrew.

**Comment by kstribrnAmzn** [comment] 2023-03-13 15:55
Closing this out since there hasn't been any further action. Feel free to reopen if needed.

**Closed by kstribrnAmzn** 2023-03-13 15:55 UTC
